# Use the distroless Java 17 image as the base image
FROM gcr.io/distroless/java21-debian12

# Copy your Java application JAR file into the image
COPY build/libs/graalvm-spring-reactor-native-0.0.1-SNAPSHOT.jar /app/graalvm-spring-reactor-native-0.0.1-SNAPSHOT.jar

# Expose the port your application listens on (if applicable)
EXPOSE 8080

# Specify the command to run when the container starts
CMD ["/app/graalvm-spring-reactor-native-0.0.1-SNAPSHOT.jar"]
