# Use the Distroless base image with libgcc dependency
FROM gcr.io/distroless/cc-debian12:nonroot

# Copy your statically-linked binary into the container
COPY build/native/nativeCompile/graalvm-spring-reactor-native /app

# Expose the port your application listens on (if applicable)
EXPOSE 8080

# Set the command to run your application when the container starts
CMD ["/app"]